import Head from "next/head";
import styles from "../styles/Home.module.css";
import Categorias from "../componentes/Categorias";
import CampoDeBusca from "../componentes/CampoDeBusca";
import Card from "../componentes/Cards";
import {listaDeProdutos, filtroLista, filtroBusca} from "../service";
import { useState } from "react";




export default function Home() {
let produtosEntradas = listaDeProdutos().filter((produto) => (produto.categoria === "Entradas"));

const [lista, setLista] = useState(produtosEntradas);
const [texto, setTexto] = useState("");

const buscaPorCategoria = (texto) => {filtroLista(texto, listaDeProdutos(), setLista, setTexto)}
const buscarProduto = (textoDigitado) => {filtroBusca(setTexto, textoDigitado, setLista, listaDeProdutos())}

  return (
    <>
      <Head>
        <title>Cadápio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Poppins&display=swap" rel="stylesheet"/>
      </Head>
      <main>

        <section className={styles.banner}>
          <div className={styles.box_titulo}>
            <h1>RESTAURANT</h1>
            <p>De pratos clássicos a criações surpreendentes, nosso cardápio é um requinte de sabores refinados</p>
          </div>
        </section>

        <section>
          <Categorias funcao={buscaPorCategoria}/>
        </section>

        <section>
        <CampoDeBusca textoInput={texto} funcao={buscarProduto} />
        </section>

        <section className={styles.container_cards}>
          <h1>Cardápio</h1>
        { lista.map( (produto) => (
          <Card 
          key={produto.id}
          nome={produto.nome}
          imagem={produto.imagem}
          categoria={produto.categoria}
          descricao={produto.descricao}
          preco={produto.preco.toFixed(2)}
          />
        ))

        }
        </section>
        
      </main>
      
    </>
  );
}
